// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webpage.proto

package cn.eagle.pubsea.webpage.proto;

public final class WebPageProto {
  private WebPageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WebPageMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string webid = 1;
    /**
     * <code>required string webid = 1;</code>
     *
     * <pre>
     * webid标示
     * </pre>
     */
    boolean hasWebid();
    /**
     * <code>required string webid = 1;</code>
     *
     * <pre>
     * webid标示
     * </pre>
     */
    java.lang.String getWebid();
    /**
     * <code>required string webid = 1;</code>
     *
     * <pre>
     * webid标示
     * </pre>
     */
    com.google.protobuf.ByteString
        getWebidBytes();

    // required bytes source = 2;
    /**
     * <code>required bytes source = 2;</code>
     *
     * <pre>
     * 来源
     * </pre>
     */
    boolean hasSource();
    /**
     * <code>required bytes source = 2;</code>
     *
     * <pre>
     * 来源
     * </pre>
     */
    com.google.protobuf.ByteString getSource();

    // required int64 dateid = 3;
    /**
     * <code>required int64 dateid = 3;</code>
     *
     * <pre>
     * 爬虫爬取的时间点, yyyymmdd格式
     * </pre>
     */
    boolean hasDateid();
    /**
     * <code>required int64 dateid = 3;</code>
     *
     * <pre>
     * 爬虫爬取的时间点, yyyymmdd格式
     * </pre>
     */
    long getDateid();

    // required string url = 4;
    /**
     * <code>required string url = 4;</code>
     *
     * <pre>
     * url
     * </pre>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 4;</code>
     *
     * <pre>
     * url
     * </pre>
     */
    java.lang.String getUrl();
    /**
     * <code>required string url = 4;</code>
     *
     * <pre>
     * url
     * </pre>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    // optional bytes title = 5;
    /**
     * <code>optional bytes title = 5;</code>
     *
     * <pre>
     * 标题
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>optional bytes title = 5;</code>
     *
     * <pre>
     * 标题
     * </pre>
     */
    com.google.protobuf.ByteString getTitle();

    // optional string timestamp = 6;
    /**
     * <code>optional string timestamp = 6;</code>
     *
     * <pre>
     * time
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional string timestamp = 6;</code>
     *
     * <pre>
     * time
     * </pre>
     */
    java.lang.String getTimestamp();
    /**
     * <code>optional string timestamp = 6;</code>
     *
     * <pre>
     * time
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    // required bytes content = 7;
    /**
     * <code>required bytes content = 7;</code>
     *
     * <pre>
     * 正文内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 7;</code>
     *
     * <pre>
     * 正文内容
     * </pre>
     */
    com.google.protobuf.ByteString getContent();

    // optional bytes titleHtml = 8;
    /**
     * <code>optional bytes titleHtml = 8;</code>
     *
     * <pre>
     * 标题html
     * </pre>
     */
    boolean hasTitleHtml();
    /**
     * <code>optional bytes titleHtml = 8;</code>
     *
     * <pre>
     * 标题html
     * </pre>
     */
    com.google.protobuf.ByteString getTitleHtml();

    // optional bytes timestampHtml = 9;
    /**
     * <code>optional bytes timestampHtml = 9;</code>
     *
     * <pre>
     * 时间戳的html
     * </pre>
     */
    boolean hasTimestampHtml();
    /**
     * <code>optional bytes timestampHtml = 9;</code>
     *
     * <pre>
     * 时间戳的html
     * </pre>
     */
    com.google.protobuf.ByteString getTimestampHtml();

    // required bytes contentHtml = 10;
    /**
     * <code>required bytes contentHtml = 10;</code>
     *
     * <pre>
     * 内容的html
     * </pre>
     */
    boolean hasContentHtml();
    /**
     * <code>required bytes contentHtml = 10;</code>
     *
     * <pre>
     * 内容的html
     * </pre>
     */
    com.google.protobuf.ByteString getContentHtml();

    // required bytes pageHtml = 11;
    /**
     * <code>required bytes pageHtml = 11;</code>
     *
     * <pre>
     * 整个页面的html
     * </pre>
     */
    boolean hasPageHtml();
    /**
     * <code>required bytes pageHtml = 11;</code>
     *
     * <pre>
     * 整个页面的html
     * </pre>
     */
    com.google.protobuf.ByteString getPageHtml();
  }
  /**
   * Protobuf type {@code cn.eagle.pubsea.webpage.proto.WebPageMessage}
   */
  public static final class WebPageMessage extends
      com.google.protobuf.GeneratedMessage
      implements WebPageMessageOrBuilder {
    // Use WebPageMessage.newBuilder() to construct.
    private WebPageMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WebPageMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WebPageMessage defaultInstance;
    public static WebPageMessage getDefaultInstance() {
      return defaultInstance;
    }

    public WebPageMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WebPageMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              webid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              source_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              dateid_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              url_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              title_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              timestamp_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              content_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              titleHtml_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              timestampHtml_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              contentHtml_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              pageHtml_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.eagle.pubsea.webpage.proto.WebPageProto.internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.eagle.pubsea.webpage.proto.WebPageProto.internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage.class, cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<WebPageMessage> PARSER =
        new com.google.protobuf.AbstractParser<WebPageMessage>() {
      public WebPageMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebPageMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WebPageMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string webid = 1;
    public static final int WEBID_FIELD_NUMBER = 1;
    private java.lang.Object webid_;
    /**
     * <code>required string webid = 1;</code>
     *
     * <pre>
     * webid标示
     * </pre>
     */
    public boolean hasWebid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string webid = 1;</code>
     *
     * <pre>
     * webid标示
     * </pre>
     */
    public java.lang.String getWebid() {
      java.lang.Object ref = webid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          webid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string webid = 1;</code>
     *
     * <pre>
     * webid标示
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWebidBytes() {
      java.lang.Object ref = webid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        webid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes source = 2;
    public static final int SOURCE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString source_;
    /**
     * <code>required bytes source = 2;</code>
     *
     * <pre>
     * 来源
     * </pre>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes source = 2;</code>
     *
     * <pre>
     * 来源
     * </pre>
     */
    public com.google.protobuf.ByteString getSource() {
      return source_;
    }

    // required int64 dateid = 3;
    public static final int DATEID_FIELD_NUMBER = 3;
    private long dateid_;
    /**
     * <code>required int64 dateid = 3;</code>
     *
     * <pre>
     * 爬虫爬取的时间点, yyyymmdd格式
     * </pre>
     */
    public boolean hasDateid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 dateid = 3;</code>
     *
     * <pre>
     * 爬虫爬取的时间点, yyyymmdd格式
     * </pre>
     */
    public long getDateid() {
      return dateid_;
    }

    // required string url = 4;
    public static final int URL_FIELD_NUMBER = 4;
    private java.lang.Object url_;
    /**
     * <code>required string url = 4;</code>
     *
     * <pre>
     * url
     * </pre>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string url = 4;</code>
     *
     * <pre>
     * url
     * </pre>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 4;</code>
     *
     * <pre>
     * url
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes title = 5;
    public static final int TITLE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString title_;
    /**
     * <code>optional bytes title = 5;</code>
     *
     * <pre>
     * 标题
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes title = 5;</code>
     *
     * <pre>
     * 标题
     * </pre>
     */
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }

    // optional string timestamp = 6;
    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private java.lang.Object timestamp_;
    /**
     * <code>optional string timestamp = 6;</code>
     *
     * <pre>
     * 时间
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string timestamp = 6;</code>
     *
     * <pre>
     * 时间
     * </pre>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timestamp = 6;</code>
     *
     * <pre>
     * 时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes content = 7;
    public static final int CONTENT_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 7;</code>
     *
     * <pre>
     * 正文内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required bytes content = 7;</code>
     *
     * <pre>
     * 正文内容
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    // optional bytes titleHtml = 8;
    public static final int TITLEHTML_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString titleHtml_;
    /**
     * <code>optional bytes titleHtml = 8;</code>
     *
     * <pre>
     * 标题html
     * </pre>
     */
    public boolean hasTitleHtml() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes titleHtml = 8;</code>
     *
     * <pre>
     * 标题html
     * </pre>
     */
    public com.google.protobuf.ByteString getTitleHtml() {
      return titleHtml_;
    }

    // optional bytes timestampHtml = 9;
    public static final int TIMESTAMPHTML_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString timestampHtml_;
    /**
     * <code>optional bytes timestampHtml = 9;</code>
     *
     * <pre>
     * 时间戳的html
     * </pre>
     */
    public boolean hasTimestampHtml() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes timestampHtml = 9;</code>
     *
     * <pre>
     * 时间戳的html
     * </pre>
     */
    public com.google.protobuf.ByteString getTimestampHtml() {
      return timestampHtml_;
    }

    // required bytes contentHtml = 10;
    public static final int CONTENTHTML_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString contentHtml_;
    /**
     * <code>required bytes contentHtml = 10;</code>
     *
     * <pre>
     * 内容的html
     * </pre>
     */
    public boolean hasContentHtml() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required bytes contentHtml = 10;</code>
     *
     * <pre>
     * 内容的html
     * </pre>
     */
    public com.google.protobuf.ByteString getContentHtml() {
      return contentHtml_;
    }

    // required bytes pageHtml = 11;
    public static final int PAGEHTML_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString pageHtml_;
    /**
     * <code>required bytes pageHtml = 11;</code>
     *
     * <pre>
     * 整个页面的html
     * </pre>
     */
    public boolean hasPageHtml() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required bytes pageHtml = 11;</code>
     *
     * <pre>
     * 整个页面的html
     * </pre>
     */
    public com.google.protobuf.ByteString getPageHtml() {
      return pageHtml_;
    }

    private void initFields() {
      webid_ = "";
      source_ = com.google.protobuf.ByteString.EMPTY;
      dateid_ = 0L;
      url_ = "";
      title_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      titleHtml_ = com.google.protobuf.ByteString.EMPTY;
      timestampHtml_ = com.google.protobuf.ByteString.EMPTY;
      contentHtml_ = com.google.protobuf.ByteString.EMPTY;
      pageHtml_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasWebid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDateid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentHtml()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageHtml()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getWebidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, source_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, dateid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, title_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, content_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, titleHtml_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, timestampHtml_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, contentHtml_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, pageHtml_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getWebidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, source_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, dateid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, title_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, content_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, titleHtml_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, timestampHtml_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, contentHtml_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, pageHtml_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.eagle.pubsea.webpage.proto.WebPageMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.eagle.pubsea.webpage.proto.WebPageProto.internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.eagle.pubsea.webpage.proto.WebPageProto.internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage.class, cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage.Builder.class);
      }

      // Construct using cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        webid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        dateid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        titleHtml_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        timestampHtml_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        contentHtml_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        pageHtml_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.eagle.pubsea.webpage.proto.WebPageProto.internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_descriptor;
      }

      public cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage getDefaultInstanceForType() {
        return cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage.getDefaultInstance();
      }

      public cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage build() {
        cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage buildPartial() {
        cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage result = new cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.webid_ = webid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dateid_ = dateid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.titleHtml_ = titleHtml_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.timestampHtml_ = timestampHtml_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.contentHtml_ = contentHtml_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.pageHtml_ = pageHtml_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage) {
          return mergeFrom((cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage other) {
        if (other == cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage.getDefaultInstance()) return this;
        if (other.hasWebid()) {
          bitField0_ |= 0x00000001;
          webid_ = other.webid_;
          onChanged();
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (other.hasDateid()) {
          setDateid(other.getDateid());
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000008;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000020;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasTitleHtml()) {
          setTitleHtml(other.getTitleHtml());
        }
        if (other.hasTimestampHtml()) {
          setTimestampHtml(other.getTimestampHtml());
        }
        if (other.hasContentHtml()) {
          setContentHtml(other.getContentHtml());
        }
        if (other.hasPageHtml()) {
          setPageHtml(other.getPageHtml());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWebid()) {
          
          return false;
        }
        if (!hasSource()) {
          
          return false;
        }
        if (!hasDateid()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!hasContentHtml()) {
          
          return false;
        }
        if (!hasPageHtml()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.eagle.pubsea.webpage.proto.WebPageProto.WebPageMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string webid = 1;
      private java.lang.Object webid_ = "";
      /**
       * <code>required string webid = 1;</code>
       *
       * <pre>
       * webid标示
       * </pre>
       */
      public boolean hasWebid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string webid = 1;</code>
       *
       * <pre>
       * webid标示
       * </pre>
       */
      public java.lang.String getWebid() {
        java.lang.Object ref = webid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          webid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string webid = 1;</code>
       *
       * <pre>
       * webid标示
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWebidBytes() {
        java.lang.Object ref = webid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          webid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string webid = 1;</code>
       *
       * <pre>
       * webid标示
       * </pre>
       */
      public Builder setWebid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        webid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string webid = 1;</code>
       *
       * <pre>
       * webid标示
       * </pre>
       */
      public Builder clearWebid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        webid_ = getDefaultInstance().getWebid();
        onChanged();
        return this;
      }
      /**
       * <code>required string webid = 1;</code>
       *
       * <pre>
       * webid标示
       * </pre>
       */
      public Builder setWebidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        webid_ = value;
        onChanged();
        return this;
      }

      // required bytes source = 2;
      private com.google.protobuf.ByteString source_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes source = 2;</code>
       *
       * <pre>
       * 来源
       * </pre>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes source = 2;</code>
       *
       * <pre>
       * 来源
       * </pre>
       */
      public com.google.protobuf.ByteString getSource() {
        return source_;
      }
      /**
       * <code>required bytes source = 2;</code>
       *
       * <pre>
       * 来源
       * </pre>
       */
      public Builder setSource(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes source = 2;</code>
       *
       * <pre>
       * 来源
       * </pre>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }

      // required int64 dateid = 3;
      private long dateid_ ;
      /**
       * <code>required int64 dateid = 3;</code>
       *
       * <pre>
       * 爬虫爬取的时间点, yyyymmdd格式
       * </pre>
       */
      public boolean hasDateid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 dateid = 3;</code>
       *
       * <pre>
       * 爬虫爬取的时间点, yyyymmdd格式
       * </pre>
       */
      public long getDateid() {
        return dateid_;
      }
      /**
       * <code>required int64 dateid = 3;</code>
       *
       * <pre>
       * 爬虫爬取的时间点, yyyymmdd格式
       * </pre>
       */
      public Builder setDateid(long value) {
        bitField0_ |= 0x00000004;
        dateid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 dateid = 3;</code>
       *
       * <pre>
       * 爬虫爬取的时间点, yyyymmdd格式
       * </pre>
       */
      public Builder clearDateid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dateid_ = 0L;
        onChanged();
        return this;
      }

      // required string url = 4;
      private java.lang.Object url_ = "";
      /**
       * <code>required string url = 4;</code>
       *
       * <pre>
       * url
       * </pre>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string url = 4;</code>
       *
       * <pre>
       * url
       * </pre>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string url = 4;</code>
       *
       * <pre>
       * url
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 4;</code>
       *
       * <pre>
       * url
       * </pre>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 4;</code>
       *
       * <pre>
       * url
       * </pre>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 4;</code>
       *
       * <pre>
       * url
       * </pre>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
        return this;
      }

      // optional bytes title = 5;
      private com.google.protobuf.ByteString title_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes title = 5;</code>
       *
       * <pre>
       * 标题
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes title = 5;</code>
       *
       * <pre>
       * 标题
       * </pre>
       */
      public com.google.protobuf.ByteString getTitle() {
        return title_;
      }
      /**
       * <code>optional bytes title = 5;</code>
       *
       * <pre>
       * 标题
       * </pre>
       */
      public Builder setTitle(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes title = 5;</code>
       *
       * <pre>
       * 标题
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000010);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }

      // optional string timestamp = 6;
      private java.lang.Object timestamp_ = "";
      /**
       * <code>optional string timestamp = 6;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string timestamp = 6;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timestamp = 6;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timestamp = 6;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timestamp = 6;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timestamp = 6;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }

      // required bytes content = 7;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 7;</code>
       *
       * <pre>
       * 正文内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bytes content = 7;</code>
       *
       * <pre>
       * 正文内容
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 7;</code>
       *
       * <pre>
       * 正文内容
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 7;</code>
       *
       * <pre>
       * 正文内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // optional bytes titleHtml = 8;
      private com.google.protobuf.ByteString titleHtml_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes titleHtml = 8;</code>
       *
       * <pre>
       * 标题html
       * </pre>
       */
      public boolean hasTitleHtml() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes titleHtml = 8;</code>
       *
       * <pre>
       * 标题html
       * </pre>
       */
      public com.google.protobuf.ByteString getTitleHtml() {
        return titleHtml_;
      }
      /**
       * <code>optional bytes titleHtml = 8;</code>
       *
       * <pre>
       * 标题html
       * </pre>
       */
      public Builder setTitleHtml(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        titleHtml_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes titleHtml = 8;</code>
       *
       * <pre>
       * 标题html
       * </pre>
       */
      public Builder clearTitleHtml() {
        bitField0_ = (bitField0_ & ~0x00000080);
        titleHtml_ = getDefaultInstance().getTitleHtml();
        onChanged();
        return this;
      }

      // optional bytes timestampHtml = 9;
      private com.google.protobuf.ByteString timestampHtml_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes timestampHtml = 9;</code>
       *
       * <pre>
       * 时间戳的html
       * </pre>
       */
      public boolean hasTimestampHtml() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes timestampHtml = 9;</code>
       *
       * <pre>
       * 时间戳的html
       * </pre>
       */
      public com.google.protobuf.ByteString getTimestampHtml() {
        return timestampHtml_;
      }
      /**
       * <code>optional bytes timestampHtml = 9;</code>
       *
       * <pre>
       * 时间戳的html
       * </pre>
       */
      public Builder setTimestampHtml(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        timestampHtml_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes timestampHtml = 9;</code>
       *
       * <pre>
       * 时间戳的html
       * </pre>
       */
      public Builder clearTimestampHtml() {
        bitField0_ = (bitField0_ & ~0x00000100);
        timestampHtml_ = getDefaultInstance().getTimestampHtml();
        onChanged();
        return this;
      }

      // required bytes contentHtml = 10;
      private com.google.protobuf.ByteString contentHtml_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contentHtml = 10;</code>
       *
       * <pre>
       * 内容的html
       * </pre>
       */
      public boolean hasContentHtml() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required bytes contentHtml = 10;</code>
       *
       * <pre>
       * 内容的html
       * </pre>
       */
      public com.google.protobuf.ByteString getContentHtml() {
        return contentHtml_;
      }
      /**
       * <code>required bytes contentHtml = 10;</code>
       *
       * <pre>
       * 内容的html
       * </pre>
       */
      public Builder setContentHtml(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        contentHtml_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contentHtml = 10;</code>
       *
       * <pre>
       * 内容的html
       * </pre>
       */
      public Builder clearContentHtml() {
        bitField0_ = (bitField0_ & ~0x00000200);
        contentHtml_ = getDefaultInstance().getContentHtml();
        onChanged();
        return this;
      }

      // required bytes pageHtml = 11;
      private com.google.protobuf.ByteString pageHtml_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes pageHtml = 11;</code>
       *
       * <pre>
       * 整个页面的html
       * </pre>
       */
      public boolean hasPageHtml() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required bytes pageHtml = 11;</code>
       *
       * <pre>
       * 整个页面的html
       * </pre>
       */
      public com.google.protobuf.ByteString getPageHtml() {
        return pageHtml_;
      }
      /**
       * <code>required bytes pageHtml = 11;</code>
       *
       * <pre>
       * 整个页面的html
       * </pre>
       */
      public Builder setPageHtml(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        pageHtml_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes pageHtml = 11;</code>
       *
       * <pre>
       * 整个页面的html
       * </pre>
       */
      public Builder clearPageHtml() {
        bitField0_ = (bitField0_ & ~0x00000400);
        pageHtml_ = getDefaultInstance().getPageHtml();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cn.eagle.pubsea.webpage.proto.WebPageMessage)
    }

    static {
      defaultInstance = new WebPageMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cn.eagle.pubsea.webpage.proto.WebPageMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rwebpage.proto\022\035cn.eagle.pubsea.webpage" +
      ".proto\"\320\001\n\016WebPageMessage\022\r\n\005webid\030\001 \002(\t" +
      "\022\016\n\006source\030\002 \002(\014\022\016\n\006dateid\030\003 \002(\003\022\013\n\003url\030" +
      "\004 \002(\t\022\r\n\005title\030\005 \001(\014\022\021\n\ttimestamp\030\006 \001(\t\022" +
      "\017\n\007content\030\007 \002(\014\022\021\n\ttitleHtml\030\010 \001(\014\022\025\n\rt" +
      "imestampHtml\030\t \001(\014\022\023\n\013contentHtml\030\n \002(\014\022" +
      "\020\n\010pageHtml\030\013 \002(\014B-\n\035cn.eagle.pubsea.web" +
      "page.protoB\014WebPageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_eagle_pubsea_webpage_proto_WebPageMessage_descriptor,
              new java.lang.String[] { "Webid", "Source", "Dateid", "Url", "Title", "Timestamp", "Content", "TitleHtml", "TimestampHtml", "ContentHtml", "PageHtml", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
